Repository AY2425S2-CS2103T-F10-3/tp, pull requests merged in 2025-03, with the labels that each got.

#42 Remove John Doe from AboutUs.md
  docs/AboutUs.md
Labels: severity.VeryLow

#58 Improve Add functionality by increment again
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Year.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/YearTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/SampleDataUtilTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#65 Improve the UI for the Help Window
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High

#71 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#75 Update Images for User Guide
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
Labels: type.Task

#81 Rewrite test cases for MainApp.java
  src/test/java/seedu/address/MainAppTest.java
Labels: priority.Low

#83 Backup old data when corrupted data detected
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
Labels: priority.High

#91 Update UserGuide.md
  docs/UserGuide.md
  docs/images/find-command-prompt.png
  docs/images/findAlexDavidResult.png
  docs/images/java-version.png
Labels: priority.High

#99 Update userGuide.md for data file related section
  docs/UserGuide.md
  docs/images/corruptedDataWarning.png
Labels: type.Enhancement, priority.High

#95 Update User Guide (Jake's end)
  docs/UserGuide.md
  docs/images/Guide_1.png
  docs/images/Guide_2.png
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
Labels: priority.High

#93 Add new labels and also improve Ui design
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.High

#106 Add assert statements for AddCommand
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: priority.High

#120 Branch jake increment del1
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/ConfirmDeleteWindow.java
  src/main/resources/view/ConfirmDeleteWindow.css
  src/main/resources/view/ConfirmDeleteWindow.fxml
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: priority.Medium

#131 Add Hide / Unhide Commands
  src/main/java/seedu/address/logic/commands/HideCommand.java
  src/main/java/seedu/address/logic/commands/UnhideCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/HideCommandTest.java
  src/test/java/seedu/address/logic/commands/UnhideCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#132 Update UserGuide.md and improve formatting
  docs/UserGuide.md
Labels: priority.Medium

#136 Delete students using tags
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#144 Refine tag feature by including priority
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Priority.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/tag/PriorityTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTags.java
Labels: priority.High

#145 Fix UML diagram for backup and update developerGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BackupOnCorruptSequenceDiagram.puml
Labels: type.Bug, priority.High, alpha-bug
