Repository AY2425S2-CS2103T-F10-3/tp, pull requests merged in 2025-04, with the labels that each got.

#155 Update UG for sort function
  docs/UserGuide.md
Labels: alpha-bug

#171 Remove proposed section in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: alpha-bug

#174 Fix incorrect YAML front matter in UserGuide.md
  docs/UserGuide.md
Labels: alpha-bug

#183 Update UG table of content and certain inconsistency in description
  docs/UserGuide.md
Labels: alpha-bug

#179 Suggest changes for the Miscellaneous information part of the UserGuide
  docs/UserGuide.md
  docs/images/Guide_1.png
Labels: type.Enhancement

#190 Update incomplete part in DG
  docs/DeveloperGuide.md
Labels: priority.High

#198 Update Instructions for Manual Testing section in DG
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
Labels: priority.High

#199 Remove incomplete subheading
  docs/DeveloperGuide.md
Labels: priority.High

#260 Fix corrupted data file not deleted after backup
  docs/DeveloperGuide.md
  docs/diagrams/BackupOnCorruptSequenceDiagram.puml
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
Labels: severity.Low

#261 Fix app crashes if priority is not valid in json file
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Priority.java
  src/test/java/seedu/address/model/tag/PriorityTest.java
Labels: severity.High

#264 Update specific missing parameter error message
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: alpha-bug

#262 Fix commands are case sensitive
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: severity.Low

#263 Fix incorrect status message for delete command
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: severity.Medium
